import type { Metadata } from "next";
import "./globals.css";
import {Navbar} from "./ui/components/Navbar"
import { Play } from 'next/font/google'

export const play = Play({
    subsets: ['latin'], display: 'swap',
    weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "NASA APIs web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    
    <html lang="en">
      <body className={`${play.className} antialased`} style={{ padding: '0px 0px', fontWeight: '700' }}>
        <header><Navbar /></header>
          <main>
         
              {children}
            
          </main>  
        <footer>© 2024 Company, Inc. All rights reserved.</footer>
      </body> 
    </html>
  );
}
